title: zaprett
description: Сайт приложения zaprett
theme: just-the-docs

# Настройки Just the Docs
#logo: /assets/images/logo.png    # путь к логотипу (опционально)
color_scheme: dark               # или light (опционально)
search_enabled: true             # поиск по сайту

# Навигация (пример)
nav:
  - Главная: index.md
  - Руководство:
      - Установка: guide/install.md
      - Использование: guide/usage.md

# URL сайта (опционально)
url: "https://username.github.io/repo"

# Локализация (опционально)
lang: ru
