title: Моя документация
description: Сайт на GitHub Pages с темой Just the Docs

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Дополнительные настройки (опционально)
color_scheme: dark
search_enabled: true
