name: Deploy VitePress site to S3 storage

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress
        run: VITEPRESS_CLEANURL=false VITEPRESS_BASE=/zapret/ VITEPRESS_HOSTNAME=https://storage.yandexcloud.net/zaprett npm run docs:build

      - name: List build output (debug)
        run: ls -la .vitepress

      - name: Configure AWS CLI for Yandex Cloud
        run: |
          pip install awscli
          aws configure set aws_access_key_id ${{ secrets.YC_S3_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.YC_S3_SECRET_KEY }}
          aws configure set region ru-central1
          aws configure set endpoint_url https://storage.yandexcloud.net

      - name: Sync files to Yandex Cloud S3
        run: |
          aws s3 sync .vitepress/dist s3://zaprett \
            --delete \
            --acl public-read \
            --exclude "*.html" \
            --cache-control "max-age=31536000"
          aws s3 sync .vitepress/dist s3://zaprett \
            --delete \
            --acl public-read \
            --exclude "*" \
            --include "*.html" \
            --cache-control "no-cache, no-store, must-revalidate"
